training:
  num_train_steps: 100000
  log_every: 100
  batch_size: 12
  subset_fraction: 0.7
  normal_fraction: 0.25

  max_grad_norm: 1.0  # 5.0
  seed: 42

  mixed_precision: "fp16"
  gradient_accumulation_steps: 1 # 1
  gradient_checkpointing: true

  fine_tune: true  # false
  fine_tune_steps: 15000

optimizer: 
  lr: 1e-5  # 1e-4
  betas: [0.9, 0.999]
  weight_decay: 0.01
  
lr_scheduler:
  num_warmup_steps: 500  # 1000
  
cfg: 
  cfg_drop_prob: 0.1  # 0.0
  guidance_scale: 3.0  # 1.0
  
validation: 
  val_steps: 5000
  max_val_batches: 25

ema:
  enabled: true
  ema_decay: 0.9999  # 0.9999

generation:
  sample_steps: ${train.validation.val_steps}
  max_samples: 128
  num_save_image: 16

metrics:
  metrics_steps: ${train.validation.val_steps}
  fd:
    dino: true
    inception: false
    num_samples: 128
  lpips:
    diversity: false
    max_pairs: 256
